# Generated by Django 5.1.15 on 2026-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_donor_email_transaction_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash')], default='MPESA', max_length=10),
        ),
    ]
