# Generated by Django 5.1.15 on 2026-08-26 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donationtype_balance'),
        ('payments', '0003_transaction_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to=settings.AUTH_USER_MODEL)),
                ('donation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='donation.donationtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
